### PR TITLE
feat: add option to transform tooltip text

### PR DESCRIPTION
**Pull request by ealves-pt**
I need to customize what is displayed in the tooltip so I've decided to add an option for that. I think others will find this useful.

### CODE REVIEW

**Comment by ealves-pt** [comment]
I need to customize what is displayed in the tooltip so I've decided to add an option for that. I think others will find this useful.

**Comment by hansmaad** [comment]
What's wrong with the existing `options.tooltipFnc`?

**Comment by ealves-pt** [comment]
@hansmaad nothing is wrong with it but I just want to format the text and leave the markup as is.

**Comment by ealves-pt** [comment]
What is the status on this PR? Any intention to merge it?

**Comment by Globegitter** [comment]
Thanks for this @ealves-pt just merged.

**Pull request merged**
